# Generated by Django 6.0.1 on 2026-07-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='captions',
            field=models.JSONField(blank=True, default=None, help_text='Subtitles: [{start, end, text}, ...] yoki null', null=True),
        ),
    ]
