# Generated by Django 6.0.1 on 2026-07-02 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Ichki nomi (foydalanuvchiga ko'rinmaydi)", max_length=255)),
                ('banner_type', models.CharField(choices=[('image', 'Rasm banner'), ('text', "Matnli e'lon"), ('html', 'HTML banner')], default='text', max_length=10)),
                ('position', models.CharField(choices=[('dashboard_top', 'Dashboard tepasi'), ('dashboard_bottom', 'Dashboard pastki'), ('sidebar', 'Sidebar'), ('fullwidth', "To'liq kenglikda (sahifalar orasida)"), ('popup', 'Popup (modal)')], default='dashboard_top', max_length=20)),
                ('text_content', models.TextField(blank=True, help_text="Matnli e'lon uchun")),
                ('image_url', models.URLField(blank=True, help_text='Rasm URL manzili')),
                ('html_content', models.TextField(blank=True, help_text="HTML banner uchun (ehtiyot bo'ling)")),
                ('link_url', models.URLField(blank=True, help_text="Bosilganda o'tadigan havola")),
                ('link_text', models.CharField(blank=True, help_text='Havola tugmasi matni', max_length=100)),
                ('bg_color', models.CharField(blank=True, default='', help_text='Fon rangi (masalan: #4F46E5 yoki gradient)', max_length=50)),
                ('text_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text="Yuqori raqam = birinchi ko'rsatiladi")),
                ('start_date', models.DateTimeField(blank=True, help_text="Boshlanish sanasi (bo'sh = darhol)", null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text="Tugash sanasi (bo'sh = cheksiz)", null=True)),
                ('impressions', models.PositiveIntegerField(default=0, help_text="Necha marta ko'rsatildi")),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Necha marta bosildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
