from django.urls import path

from .views import (
    AdminUserListView,
    ProfileView,
    RegisterView,
    admin_delete_article,
    admin_statistics,
    ban_user,
    change_password,
    google_auth,
    password_reset_confirm,
    password_reset_request,
    public_stats,
    resend_verification,
    set_admin,
    verify_email,
    get_telegram_link,
    unlink_telegram,
    telegram_webhook,
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("verify-email/", verify_email, name="verify-email"),
    path("resend-verification/", resend_verification, name="resend-verification"),
    path("me/", ProfileView.as_view(), name="me"),
    path("change-password/", change_password, name="change-password"),
    path("password-reset/", password_reset_request, name="password-reset"),
    path("password-reset/confirm/", password_reset_confirm, name="password-reset-confirm"),
    path("google-auth/", google_auth, name="google-auth"),
    path("telegram-link/", get_telegram_link, name="telegram-link"),
    path("telegram-unlink/", unlink_telegram, name="telegram-unlink"),
    path("telegram-webhook/", telegram_webhook, name="telegram-webhook"),
    path("admin/users/", AdminUserListView.as_view(), name="admin-users"),
    path("admin/users/<int:user_id>/set-admin/", set_admin, name="set-admin"),
    path("admin/users/<int:user_id>/ban/", ban_user, name="ban-user"),
    path("admin/articles/<int:article_id>/delete/", admin_delete_article, name="admin-delete-article"),
    path("admin/statistics/", admin_statistics, name="admin-statistics"),
    path("public-stats/", public_stats, name="public-stats"),
]
