# Generated by Django 6.0.1 on 2026-07-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
