# Generated by Django 6.0.1 on 2026-07-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0002_uzbek_grade_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['semester', 'name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('1', '1-semestr'), ('2', '2-semestr'), ('3', '3-semestr'), ('4', '4-semestr'), ('5', '5-semestr'), ('6', '6-semestr'), ('7', '7-semestr'), ('8', '8-semestr'), ('9', '9-semestr'), ('10', '10-semestr'), ('11', '11-semestr'), ('12', '12-semestr')], default='1', max_length=2),
        ),
    ]
