# Generated by Django 6.0.1 on 2026-07-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0003_add_semester_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='scale_type',
            field=models.CharField(choices=[('5', "5 ballik (O'zbekiston)"), ('4', '4.0 Letter Grade (US/International)'), ('100', '100 ballik shkala'), ('ects', 'ECTS (Yevropa tizimi)')], default='5', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('1', '1-semestr'), ('2', '2-semestr'), ('3', '3-semestr'), ('4', '4-semestr'), ('5', '5-semestr'), ('6', '6-semestr'), ('7', '7-semestr'), ('8', '8-semestr')], default='1', max_length=2),
        ),
    ]
